name: "Build & push to cache"
on:
  push:
    branches:
      - main
jobs:
  tests:
    name: "Build ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: nixosConfigurations.sandhose-desktop.config.system.build.toplevel
          - os: ubuntu-22.04
            target: nixosConfigurations.spaetzle.config.system.build.toplevel
          - os: macos-14
            target: darwinConfigurations.sandhose-laptop-m1.system

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: sandhose
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - name: Build system
        env:
          TARGET: "github:${{ github.repository }}/${{ github.ref }}#${{ matrix.target }}"
        run: nix build $TARGET --fallback --keep-going --log-format raw --print-build-logs
