name: "Build & push to cache"
on:
  push:
    branches:
      - master
jobs:
  tests:
    name: "Build ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            target: nixosConfigurations.sandhose-desktop.config.system.build.toplevel
          - os: ubuntu-20.04
            target: nixosConfigurations.spaetzle.config.system.build.toplevel
          - os: macos-11
            target: darwinConfigurations.sandhose-laptop.system

    steps:
      - name: Create Nix mount point
        if: contains(matrix.os, 'ubuntu')
        run: sudo mkdir /nix

      - name: Maximize build space
        uses: easimon/maximize-build-space@v9
        if: contains(matrix.os, 'ubuntu')
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          build-mount-path: "/nix"
          overprovision-lvm: "true"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        if: contains(matrix.os, 'macos')
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Nix
        if: contains(matrix.os, 'ubuntu')
        uses: cachix/install-nix-action@v25

      - uses: cachix/cachix-action@v13
        with:
          name: sandhose
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - name: Build system
        env:
          TARGET: ".#${{ matrix.target }}"
        run: nix build $TARGET --show-trace --fallback --keep-going -v --log-format raw
