name: "Build & push to cache"
on:
  push:
    branches:
      - master
jobs:
  tests:
    name: "Build ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: nixosConfigurations.sandhose-desktop.config.system.build.toplevel
          - os: ubuntu-22.04
            target: nixosConfigurations.spaetzle.config.system.build.toplevel
          - os: macos-14
            target: darwinConfigurations.sandhose-laptop-m1.system

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: sandhose
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - name: Build system
        env:
          TARGET: ".#${{ matrix.target }}"
        run: nix build $TARGET --show-trace --fallback --keep-going -v --log-format raw
