name: "Build pull request"
on:
  pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: .#nixosConfigurations.sandhose-desktop.config.system.build.toplevel
          - os: ubuntu-20.04
            target: .#nixosConfigurations.spaetzle.config.system.build.toplevel
          - os: macos-10.15
            target: .#darwinConfigurations.sandhose-laptop.system

    steps:
      - name: Create Nix mount point
        if: contains(matrix.os, 'ubuntu')
        run: mkdir /nix

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        if: contains(matrix.os, 'ubuntu')
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          build-mount-path: "/nix"

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v8
        with:
          name: sandhose
          skipPush: true

      - name: Build system
        env:
          TARGET: "${{ matrix.target }}"
        run: nix build $TARGET --show-trace
