name: "Update lock file"
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/sandhose/nix-flakes-installer/releases/download/nix-2.4pre20201203_8ad2c9c/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Git author
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'noreply@github.com'

      - name: Update lock file
        run: nix flake update --no-registries --recreate-lock-file --commit-lock-file

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
