name: "Update lock file"
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: tibdex/github-app-token@v1.8
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git author
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'noreply@github.com'

      - name: Update lock file
        run: nix flake update --no-registries --commit-lock-file

      - name: Get commit message
        id: commit
        run: |
          delimiter="$(openssl rand -hex 16)"
          echo "message<<${delimiter}" >> "${GITHUB_OUTPUT}"
          git log -1 --pretty=%B | tail +3 | awk -f ./misc/flake-to-markdown.awk >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          title: "Automated Flake update"
          body: "${{ steps.commit.outputs.message }}"
          delete-branch: true
